function getListDishes() {
    const items = [
		"Canh chua cá lóc",
		"Canh chua cá hú",
		"Canh chua tôm",
		"Canh chua rau muống",
		"Canh chua cá bớp",
		"Canh chua đầu cá hồi",
		"Canh chua lươn",
		"Canh chua chay",
		"Canh rau muống",
		"Canh gà lá giang",
		"Canh khổ qua dồn thịt",
		"Canh khổ qua dồn cá thác lác",
		"Canh trứng cà chua",
		"Canh đậu hũ cà chua",
		"Canh khoai mỡ nấu tôm tươi",
		"Canh bí đao nấu xương",
		"Canh cua đồng mồng tơi",
		"Canh rau dền tôm",
		"Canh rau dền thịt băm",
		"Canh cá thác lác",
		"Canh hoa thiên lý",
		"Canh dưa chua sườn heo",
		"Canh dưa chua nấu bò",
		"Canh hẹ đậu phụ",
		"Canh bí đỏ thịt băm",
		"Canh bầu nấu tôm",
		"Canh bầu nấu hến",
		"Canh sấu thịt băm",
		"Canh hến nấu khế chua",
		"Canh xà lách xoong",
		"Canh gà hầm củ sen",
		"Canh nghêu, khế, cà chua, thì là",
		"Canh cá điêu hồng nấu ngót",
		"Canh rong biển nấu đậu hũ và thịt băm",
		"Canh sườn non nấu rau củ",
		"Canh đuôi heo hầm củ cải trắng",
		"Canh gà hạt sen táo đỏ",
		"Canh tần ô nấu mực viên",
		"Canh cải ngọt nấu thịt nạc",
		"Canh kim chi sườn non",
		"Canh mướp thịt băm",
		"Canh khoai sọ hầm xương rau cải",
        "Canh rau đay mướp và tôm khô",		
		"Canh giò heo hầm đu đủ",
		"Canh giò heo hầm hạt sen",
		"Canh giò heo hầm rau củ",
		"Canh giò heo hầm bí xanh",
		"Canh củ sen giò heo",		
		"Canh rau ngót thịt băm",
		"Cá trê chiên giòn chấm mắm gừng",
		"Cá trê kho tiêu",
		"Cá lóc kho tộ",
		"Cá chim chiên giòn",
		"Cá thu chiên",
		"Cá thu sốt cà chua",
		"Cá thu rim tiêu gừng",
		"Cá thu om nước dừa",
		"Cá ngừ đại dương nướng",
		"Cá chẽm kho tộ",
		"Cá chẽm chiên sả ớt",
		"Cá chẽm hấp",
		"Cá chẽm nướng",
		"Cá tuyết phi lê chiên xù",
		"Cá tuyết nướng tỏi",
		"Cá rô chiên giòn",
		"Cá rô kho tiêu",
		"Cá rô kho thịt ba chỉ",		
        "Cá hú kho nước dừa tươi",
        "Cá diêu hồng chiên tươi",
		"Cá chép om dưa",
		"Cá nục hấp chiên giòn",
		"Cá bạc má kho",
		"Cá cơm kho cay",
		"Cá kèo kho tiêu",
		"Cá kèo kho rau răm",
		"Cá kèo nướng muối ớt",
		"Cá hấp cuốn bánh tráng",
		"Cá hồi nướng tiêu chanh",
		"Chả cá",		
        "Gà chiên nước mắm",
		"Gà kho gừng",
		"Gà kho sả",
		"Gà luộc chấm mắm gừng",
		"Gà rô ti",
		"Gà quay",
		"Gà nướng muối ớt",
		"Đùi gà chiên bơ",
		"Cánh gà nướng mật ong",
		"Cánh gà chiên nước mắm",
		"Cà ri gà",
		"Giá xào lòng gà",
		"Vịt om sấu",
		"Vịt nấu chao",
		"Vịt kho gừng",
		"Vịt quay",
		"Chim cút chiên",
		"Chim cút tẩm ngũ vị rán",
		"Bồ câu quay",
		"Mực trứng chiên",
		"Mực hấp mắm gừng",
		"Mực nhồi thịt rim",
		"Mực nhồi thịt hấp",
		"Mực nhồi thịt chiên",
		"Mực nhồi thịt sốt cà chua",
		"Mực xào chua ngọt",
		"Ếch kho sả ớt",
        "Thịt bò xào mắm ruốc",
		"Thịt chân giò luộc",
		"Thịt ba chỉ luộc",
		"Thịt ba chỉ kho tiêu",
		"Thịt ba chỉ xốt đậu phụ cà chua",
		"Thịt ba chỉ muối chiên",
		"Ba rọi heo hun khói cuộn rau củ",
		"Thịt băm sốt cà chua",
        "Thịt luộc cà pháo mắm tôm",
		"Thịt bò xào ớt chuông, cần tỏi",
        "Thịt viên sốt cà chua",
        "Thịt kho trứng",
		"Thịt kho đậu hũ",
		"Heo quay xào cải chua",
		"Kho quẹt tôm khô tóp mỡ",
		"Giò heo kho",
		"Móng giò luộc",
		"Bắp giò heo hun khói",
		"Bao tử cá basa xào",
		"Bao tử hầm tiêu xanh",
		"Chả lụa kho tiêu",
		"Chả cá sốt cà",
		"Tôm hấp mướp",
        "Tôm chiên xù",
		"Tôm chiên sả ớt",
        "Tôm cuộn khoai tây",
		"Tôm rim mặn",
		"Bò hấp sả",
        "Bò xào lúc lắc",
		"Bò hầm khoai tây cà rốt",
		"Bắp bò xào cần tỏi",
		"Bê xào thập cẩm",
		"Đậu cove xào thịt bò",
		"Dưa nấu bò",
		"Sườn cốt lếch chiên",
		"Sườn non sốt cam",
		"Sườn non kho thơm",
		"Sườn nướng",
		"Sườn xào chua ngọt",
        "Đậu hủ dồn thịt sốt cà chua",
        "Đậu phụ luộc",
		"Đậu hũ chiên giòn",
		"Đậu phụ rán",
		"Đậu hũ nhồi thịt rán",
		"Đậu đũa xào",
		"Trứng cuộn",
		"Trứng chiên",
		"Trứng đúc nấm",
		"Trứng cá rán hành thì là",
		"Trứng chiên thịt",
		"Su hào xào trứng",
		"Cua chưng hột vịt kiểu Trung Hoa",
		"Nấm rơm chưng hột vịt",
		"Mắm chưng trứng muối",
		"Rau muống luộc",
		"Rau muống xào tỏi",
        "Rau cải bắp luộc",
        "Rau củ quả luộc",
        "Rau cải xoong xào tỏi",
        "Rau bắp cải xào cà chua",
        "Rau lang xào",                       
        "Rau mồng tơi luộc",
        "Cà muối",
        "Dưa chua, cà muối",
        "Cà tím tẩm bột chiên giòn",
		"Cà tím nhồi thịt nướng",
        "Nấm xào",
        "Súp lơ luộc",
        "Mướp hương xào hành",        
        "Khoai tây chiên",
        "Hoa bí xào tỏi",
        "Ngọn su su xào tỏi",        
        "Dưa chuột chẻ",       
        "Dưa chua xào",
        "Bí xanh luộc",
        "Su su xào tỏi",
        "Bắp cải xào", 
		"Ngô chiên",
		"Khoai tây tẩm bột chiên giòn",
		"Xoài tráng miệng",
        "Nước cam",
		"Hoa quả tráng miệng",      	
    ];
    return items;
}