function getListDishes() {
    const items = {
        item001: "Gà chiên nước mắm",
        item002: "Cá trê kho tiêu",
        item003: "Cá hú kho",
        item004: "Cá diêu hồng chiên tươi",
        item005: "Đậu hủ dồn thịt sốt cà chua",
        item006: "Gà kho gừng",
        item007: "Giò heo kho",
        item008: "Thịt bò xào mắm ruốc",
        item009: "Sườn cốt lếch chiên",
        item010: "Canh dưa nấu bò",
        item011: "Canh rau đay mướp",
        item012: "Thịt chân giò luộc",
        item013: "Đậu cove xào thịt bò",
        item014: "Rau muống luộc",
        item015: "Mực trứng chiên",
        item016: "Tôm hấp mướp",
        item017: "Tôm chiên xù",
        item018: "Rau muống xào tỏi",
        item019: "Vịt om sấu",
        item020: "Đậu phụ luộc",
        item021: "Sườn non sốt cam",
        item022: "Mướp hương xào hành",
        item023: "Canh rau bí",
        item024: "Khoai tây chiên",
        item025: "Bắp giò heo hun khói",
        item026: "Đùi gà chiên bơ",
        item027: "Canh bầu nấu tôm",
        item028: "Rau cải bắp luộc",
        item029: "Mực hấp mắm gừng",
        item030: "Hoa bí xào tỏi",
        item031: "Canh cải nấu thịt nạc",
        item032: "Đậu hũ chiên giòn",
        item033: "Ba rọi heo hun khói cuộn rau củ",
        item034: "Trứng cuộn",
        item035: "Ngọn su su xào tỏi",
        item036: "Canh móng giò nấu măng",
        item037: "Dưa nấu bò",
        item038: "Dưa chuột chẻ",
        item039: "Tôm chiên sả ớt",
        item040: "Tôm cuộn khoai tây",
        item041: "Đậu phụ rán",
        item042: "Dưa chua xào",
        item043: "Bí xanh luộc",
        item044: "Trứng chiên",
        item045: "Cá chép om dưa",
        item046: "Rau củ quả luộc",
        item047: "Canh khoai sọ hầm xương rau cải",
        item048: "Bê xào thập cẩm",
        item049: "Cá rô chiên xù",
        item050: "Bò hấp sả",
        item051: "Bò xào lúc lắc",
        item052: "Canh rau dền tôm",
        item053: "Chim cút chiên",
        item054: "Ngô chiên",
        item055: "Bắp bò xào cần tỏi",
        item056: "Chim cút tẩm ngũ vị rán",
        item057: "Cà muối",
        item058: "Hoa quả tráng miệng",
        item059: "Canh bí nấu xương",
        item060: "Thịt ba chỉ luộc",
        item061: "Su su xào tỏi",
        item062: "Dưa chua, cà muối",
        item063: "Trứng đúc nấm",
        item064: "Rau cải xoong xào tỏi",
        item065: "Thịt băm sốt cà chua",
        item066: "Xoài tráng miệng",
        item067: "Nước cam",
        item068: "Đậu hũ nhồi thịt rán",
        item069: "Rau bắp cải xào cà chua",
        item070: "Canh sườn nấu chua",
        item071: "Bò hầm khoai tây cà rốt",
        item072: "Canh trai nấu hành răm",
        item073: "Thịt ba chỉ xốt đậu phụ cà chua",
        item074: "Thịt luộc",
        item075: "Canh rau ngót",
        item076: "Trứng cá rán hành thì là",
        item077: "Đậu đũa xào",
        item078: "Canh rau cải xanh",
        item079: "Khoai tây tẩm bột chiên giòn",
        item080: "Tôm rim mặn",
        item081: "Giá xào lòng gà",
        item082: "Cà tím tẩm bột chiên giòn",
        item083: "Canh trứng cà chua",
        item084: "Bắp cải xào",
        item085: "Cá bạc má kho",
        item086: "Su hào xào trứng",
        item087: "Canh mướp thịt băm",
        item088: "Móng giò luộc",
        item089: "Bao tử cá basa xào",
        item090: "Thịt bò xào ớt chuông, cần tỏi",
        item091: "Thịt viên sốt cà chua",
        item092: "Thịt kho trứng",
        item093: "Súp lơ luộc",
        item094: "Canh rau muống",
        item095: "Gà luộc",
        item096: "Sườn nướng",
        item097: "Cá chim chiên giòn",
        item098: "Cà tím nhồi thịt nướng",
        item099: "Nấm xào",
        item100: "Rau lang xào",
        item101: "Canh khoai mỡ",
        item102: "Cá thu chiên",
        item103: "Trứng chiên thịt",
        item104: "Rau mồng tơi luộc",
        item105: "Cá thu sốt cà chua",
    };
    return items;
}