function getListCourses() {
    const courses = {
        course001: "Gà chiên nước mắm",
        course002: "Cá trê kho tiêu",
        course003: "Cá hú kho",
        course004: "Cá diêu hồng chiên tươi",
        course005: "Đậu hủ dồn thịt sốt cà chua",
        course006: "Gà kho gừng",
        course007: "Giò heo kho",
        course008: "Thịt bò xào mắm ruốc",
        course009: "Sườn cốt lếch chiên",
        course010: "Canh dưa nấu bò",
        course011: "Canh rau đay mướp",
        course012: "Thịt chân giò luộc",
        course013: "Đậu cove xào thịt bò",
        course014: "Rau muống luộc",
        course015: "Mực trứng chiên",
        course016: "Tôm hấp mướp",
        course017: "Tôm chiên xù",
        course018: "Rau muống xào tỏi",
        course019: "Vịt om sấu",
        course020: "Đậu phụ luộc",
        course021: "Sườn non sốt cam",
        course022: "Mướp hương xào hành",
        course023: "Canh rau bí",
        course024: "Khoai tây chiên",
        course025: "Bắp giò heo hun khói",
        course026: "Đùi gà chiên bơ",
        course027: "Canh bầu nấu tôm",
        course028: "Rau cải bắp luộc",
        course029: "Mực hấp mắm gừng",
        course030: "Hoa bí xào tỏi",
        course031: "Canh cải nấu thịt nạc",
        course032: "Đậu hũ chiên giòn",
        course033: "Ba rọi heo hun khói cuộn rau củ",
        course034: "Trứng cuộn",
        course035: "Ngọn su su xào tỏi",
        course036: "Canh móng giò nấu măng",
        course037: "Dưa nấu bò",
        course038: "Dưa chuột chẻ",
        course039: "Tôm chiên sả ớt",
        course040: "Tôm cuộn khoai tây",
        course041: "Đậu phụ rán",
        course042: "Dưa chua xào",
        course043: "Bí xanh luộc",
        course044: "Trứng chiên",
        course045: "Cá chép om dưa",
        course046: "Rau củ quả luộc",
        course047: "Canh khoai sọ hầm xương rau cải",
        course048: "Bê xào thập cẩm",
        course049: "Cá rô chiên xù",
        course050: "Bò hấp sả",
        course051: "Bò xào lúc lắc",
        course052: "Canh rau dền tôm",
        course053: "Chim cút chiên",
        course054: "Ngô chiên",
        course055: "Bắp bò xào cần tỏi",
        course056: "Chim cút tẩm ngũ vị rán",
        course057: "Cà muối",
        course058: "Hoa quả tráng miệng",
        course059: "Canh bí nấu xương",
        course060: "Thịt ba chỉ luộc",
        course061: "Su su xào tỏi",
        course062: "Dưa chua, cà muối",
        course063: "Trứng đúc nấm",
        course064: "Rau cải xoong xào tỏi",
        course065: "Thịt băm sốt cà chua",
        course066: "Xoài tráng miệng",
        course067: "Nước cam",
        course068: "Đậu hũ nhồi thịt rán",
        course069: "Rau bắp cải xào cà chua",
        course070: "Canh sườn nấu chua",
        course071: "Bò hầm khoai tây cà rốt",
        course072: "Canh trai nấu hành răm",
        course073: "Thịt ba chỉ xốt đậu phụ cà chua",
        course074: "Thịt luộc",
        course075: "Canh rau ngót",
        course076: "Trứng cá rán hành thì là",
        course077: "Đậu đũa xào",
        course078: "Canh rau cải xanh",
        course079: "Khoai tây tẩm bột chiên giòn",
        course080: "Tôm rim mặn",
        course081: "Giá xào lòng gà",
        course082: "Cà tím tẩm bột chiên giòn",
        course083: "Canh trứng cà chua",
        course084: "Bắp cải xào",
        course085: "Cá bạc má kho",
        course086: "Su hào xào trứng",
        course087: "Canh mướp thịt băm",
        course088: "Móng giò luộc",
        course089: "Bao tử cá basa xào",
        course090: "Thịt bò xào ớt chuông, cần tỏi",
        course091: "Thịt viên sốt cà chua",
        course092: "Thịt kho trứng",
        course093: "Súp lơ luộc",
        course094: "Canh rau muống",
        course095: "Gà luộc",
        course096: "Sườn nướng",
        course097: "Cá chim chiên giòn",
        course098: "Cà tím nhồi thịt nướng",
        course099: "Nấm xào",
        course100: "Rau lang xào",
        course101: "Canh khoai mỡ",
        course102: "Cá thu chiên",
        course103: "Trứng chiên thịt",
        course104: "Rau mồng tơi luộc",
        course105: "Cá thu sốt cà chua",
    };
    return courses;
}